[core]
workspace_base="/workspace"
runtime = "local"
disable_color = true
search_api_key = "{tavily_key}"
save_trajectory_path = "/helper/openhands_traj"

[llm]
model="openai/{code_model}" # openai means openai-compatible endpoint, not OpenAI models
api_key="{api_key}"
base_url="{base_url}"
input_cost_per_token = 1.0
output_cost_per_token = 1.0
max_message_chars = 100000

[sandbox]
user_id = 1000
timeout = 3600


[mcp]
# shttp_servers = [
#     # Streamable HTTP server with API key authentication
#     {url="https://mcp.tavily.com/mcp/?tavilyApiKey={tavily_key}", api_key="{tavily_key}"}
# ]
shttp_servers = []
stdio_servers = []
sse_servers = []