[core]
workspace_base="/workspace"
runtime = "docker"
disable_color = true
search_api_key = "{tavily_key}"
save_trajectory_path = "{openhands_traj_path}"
run_as_openhands = false
debug = true

[llm]
model="openai/{code_model}" # openai means openai-compatible endpoint, not OpenAI models
api_key="{api_key}"
base_url="{base_url}"
input_cost_per_token = 1.0
output_cost_per_token = 1.0
max_message_chars = 100000
native_tool_calling = true
retry_max_wait=60

[sandbox]
user_id = 3407
timeout = 3600
runtime_container_image = "{runtime_container_image}"


[mcp]
# shttp_servers = [
#     # Streamable HTTP server with API key authentication
#     {url="https://mcp.tavily.com/mcp/?tavilyApiKey={tavily_key}", api_key="{tavily_key}"}
# ]
shttp_servers = []
stdio_servers = []
sse_servers = []

[security]
security_analyzer = "none"
