[core]
runtime = "docker"
disable_color = true
search_api_key = "{tavily_key}"
save_trajectory_path = "{openhands_traj_path}"
run_as_openhands = false
debug = true
default_agent = "{default_agent}"

[llm]
model = "openai/{code_model}"  # openai means openai-compatible endpoint, not OpenAI models
api_key = "{api_key}"
base_url = "{base_url}"
input_cost_per_token = 1.0
output_cost_per_token = 1.0
max_message_chars = 5000
max_input_tokens = {max_context_token_cnt}
native_tool_calling = true
retry_max_wait = 60
log_completions_folder = "{log_completions_folder}"
log_completions = true

[llm.condenser]
model = "openai/{code_condenser_model}"  # openai means openai-compatible endpoint, not OpenAI models
api_key = "{condenser_api_key}"
base_url = "{condenser_base_url}"

[condenser]
type = "llm"
llm_config = "condenser"
keep_first = 1
max_size = 30

[sandbox]
volumes = "{sandbox_volumes}"
user_id = 3407
timeout = 3600
runtime_container_image = "{runtime_container_image}"
enable_gpu = true
docker_runtime_kwargs = { mem_limit = "16g" }
# https://docker-py.readthedocs.io/en/stable/containers.html?highlight=run#docker.models.containers.ContainerCollection.run

[mcp]
shttp_servers = [
  # Streamable HTTP server with API key authentication
  { url = "https://mcp.tavily.com/mcp/?tavilyApiKey={tavily_key}", api_key = "{tavily_key}" },
  # Streamable HTTP server with no authentication
  { url = "http://localhost:{analyze_file_vlm_port}/mcp", timeout = 120 },
]
# shttp_servers = []
# stdio_servers = [
#     { name="analyze_file_vlm", command="python", args=["-m", "openlens_ai.tools.analyze_file_vlm", "--config", "{config_path}"] }
# ]
sse_servers = []

[security]
security_analyzer = "none"
