# Base image with Python and Conda
# FROM nvidia/cuda:12.6.2-devel-ubuntu22.04

FROM python:3.12
USER root

# Set environment variables to avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Update package index and install dependencies
RUN apt-get update
RUN apt-get install -y --fix-missing \
    wget \
    curl \
    gnupg \
    lsb-release \
    build-essential \
    vim \
    make \
    git \
    openssl \
    tmux \
    ruby

RUN apt-get install -y texlive-full
