[project]
name = "openlens_ai"
version = "0.0.1"
description = "Fully Autonomous Research Agent for Health Infomatics"
authors = [
    { name = "Yuxiao Cheng", email = "cyx22@mails.tsinghua.edu.cn" },
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "langgraph>=0.2.6",
    "python-dotenv>=1.0.1",
    "streamlit",
    "numpy",
    "vllm",
    "litellm",
    "loguru",
    "modelscope",
    "langchain",
    "typing_extensions",
    "numpy",
    "beautifulsoup4",
    "PyPDF2",
    "feedparser",
    "httpx",
    "mcp",
    "pydantic",
    "markdown",
    "langchain_tavily",
    "streamlit_scrollable_textbox",
    "langchain_openai",
    "langchain_mcp_adapters",
    "pygraphviz",
    "PyMuPDF"
]


[project.optional-dependencies]

[build-system]
requires = ["setuptools>=73.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
openlens-cli = "openlens_ai.build_graph:cli_main"
openlens-ui = "openlens_ai.frontend:main"

[tool.setuptools]
py-modules = ["openlens_ai"]
packages = ["openlens_ai", "openlens_ai.utils", "openlens_ai.tools", "openlens_ai.agents"]
package-data = {"openlens_ai" = ["openlens_ai/prompts/*", "openlens_ai/tools/latex_template/neurips/*", "openlens_ai/tools/openhands_configs/*", ]}
include-package-data = true