[build-system]
build-backend = "setuptools.build_meta"

requires = [ "setuptools>=73", "wheel" ]

[project]
name = "openlens-ai"
version = "0.0.1"
description = "Fully Autonomous Research Agent for Health Infomatics"
readme = "README.md"
authors = [
  { name = "Yuxiao Cheng", email = "cyx22@mails.tsinghua.edu.cn" },
]
requires-python = ">=3.11"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
dependencies = [
  "beautifulsoup4",
  "feedparser",
  "httpx",
  "langchain",
  "langchain-mcp-adapters",
  "langchain-openai",
  "langchain-tavily",
  "langgraph>=0.2.6",
  "litellm",
  "litellm[proxy]",
  "loguru",
  "markdown",
  "mcp",
  "modelscope",
  "numpy",
  "pydantic",
  "pymupdf",
  "pypdf",
  "python-dotenv>=1.0.1",
  "streamlit",
  "streamlit[pdf]",
  "typing-extensions",
  "vllm",
  "pillow",
  "Authlib", 
  "fastmcp",
  "graphviz",
  "html2image",
  "streamlit-autorefresh"
]

[project.scripts]
openlens-cli = "openlens_ai.build_graph:cli_main"
openlens-ui = "openlens_ai.frontend:main"

[tool.setuptools]
py-modules = [ "openlens_ai" ]
packages = [ "openlens_ai", "openlens_ai.utils", "openlens_ai.tools", "openlens_ai.agents" ]
# package-data = {"openlens_ai" = ["openlens_ai/prompts/*", "openlens_ai/tools/latex_template/neurips/*", "openlens_ai/tools/openhands_configs/*", ]}
include-package-data = true
