[core]
workspace_base="/workspace"
runtime = "local"
disable_color = true

[llm]
model="openai/{code_model}" # openai means openai-compatible endpoint, not OpenAI models
api_key="{api_key}"
base_url="{base_url}"

[sandbox]
user_id = 1000
timeout = 300

[mcp]
shttp_servers = [
    # Streamable HTTP server with API key authentication
    {url="https://mcp.tavily.com/mcp/?tavilyApiKey={tavily_key}", api_key="your-api-key"}
]