[core]
workspace_base="/workspace"
runtime = "local"
disable_color = true

[llm]
model="openai/{code_model}" # openai means openai-compatible endpoint, not OpenAI models
api_key="{api_key}"
base_url="{base_url}"

[sandbox]
user_id = 1000
timeout = 300

[mcp]
stdio_servers = [
    {name="fetch", command="uvx", args=["mcp-server-fetch"]},
]