litellm_settings:
  num_retries: 3
  callbacks:
    - litellm_logger.proxy_handler_instance
  cache: True
  cache_params:
    type: disk
    disk_cache_dir: outputs/.litellm_cache
model_list:
  - litellm_params:
      api_base: https://cloud.infini-ai.com/maas/v1/
      api_key: sk-uewsuzpc332yhydw
      model: openai/glm-4.5-air
    model_name: glm-4.5-air
  - litellm_params:
      api_base: https://cloud.infini-ai.com/maas/v1/
      api_key: sk-uewsuzpc332yhydw
      model: openai/glm-4.6
    model_name: glm-4.6
  - litellm_params:
      api_base: https://cloud.infini-ai.com/maas/v1/
      api_key: sk-uewsuzpc332yhydw
      model: openai/minimax-m2
    model_name: minimax-m2
  - litellm_params:
      api_base: https://cloud.infini-ai.com/maas/v1/
      api_key: sk-uewsuzpc332yhydw
      model: openai/glm-4.1v-9b-thinking
    model_name: glm-4.1v-9b-thinking
  - litellm_params:
      api_base: https://cloud.infini-ai.com/maas/v1/
      api_key: sk-uewsuzpc332yhydw
      model: openai/glm-4.5v
    model_name: glm-4.5v
  - litellm_params:
      api_base: http://127.0.0.1:8000/v1/
      api_key: "0"
      model: openai/llm
    model_name: local-llm
  - litellm_params:
      api_base: http://127.0.0.1:8001/v1/
      api_key: "0"
      model: openai/llm
    model_name: local-llm
  # - litellm_params:
  #     api_base: https://cloud.infini-ai.com/maas/v1/
  #     api_key: sk-uewsuzpc332yhydw
  #     model: openai/glm-4.5-air
  #   model_name: local-llm
  - litellm_params:
      model: cohere/bge-reranker-v2-m3
      api_key: sk-m4lzji6forjsglbj
      api_base: https://cloud.infini-ai.com/maas/v1/rerank
    model_name: bge-reranker-v2-m3
  
router_settings:
  fallbacks:
    - local-llm:
        - glm-4.5-air
  routing_strategy: simple-shuffle
